### ISSUE TITLE
The Codespace is not available..

### ISSUE THREAD

**Issue by JaylaSimp4U** [thegreatestgiant/novnc#10]
Everytime when i press new code and it says "setting up your codespace" after that it pops out saying "The Codespace is not available"..

![Codespace not available](https://github.com/thegreatestgiant/novnc/assets/63930262/85f11741-44d3-4552-8262-9775008125de)

**Comment by Markus2Warkus** [comment]
Yeah, that's happening for me too! I don't know why its not working but I emailed  @thegreatestgiant and they still haven't gotten back to me, maybe their working so hard to fix it that they can't respond? but I'm not so sure...

**Comment by OnlyAnaya1ne** [comment]
Same thing happen to me too but this needa be fixed soon asap..

**Comment by feeshmaster** [comment]
It’s the only thing i can use discord on :(

**Comment by Markus2Warkus** [comment]
@feeshmaster try 
[ ](https://car.fishoho.com/school/hvtrs8%2F-dksaopd%2Ccmm-cjalnglq%2FBmg%2F30%3A76315383365%3B9591)
