### ISSUE TITLE
the codespace isn't available?

### ISSUE THREAD

**Issue by Markus2Warkus** [thegreatestgiant/novnc#12]
so I just wanted to use (beta.character.ai) and i opened the noVNC codespace and it loaded and then it said the container needed to be repaired so i did that and then it said it wasn't available and my friend reached out but @thegreatestgiant still hasn't gotten back to them and  i don't understand why but i took a video so here it is just so you can see what happens when i try to open a new codespace....i'm sad now because i can't use beta.character.ai 
[Screen recording 2023-05-31 11.06.50 AM.webm](https://github.com/thegreatestgiant/novnc/assets/135157118/f7de5edd-e19c-4023-b60f-f56c45264fbd)

**Comment by OnlyAnaya1ne** [comment]
Yeah, same-thing happen to mine too..

**Comment by KyceAbdallah** [comment]
Same @thegreatestgiant we need help
[Screen recording 2023-06-02 3.07.45 PM.webm](https://github.com/thegreatestgiant/novnc/assets/90739617/c1c4f1e8-e853-47cd-a5ba-99e949ce0c29)

**Comment by feeshmaster** [comment]
Yeah same for me
