### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by XKingZisGay** [thegreatestgiant/novnc#16]
It says error when I create a new codespace then it recovers it however the ports are gone so can you fix this please. Even in terminal its says codespace needs to be recovered please fix the system.

**Comment by GoldWristX** [comment]
Same I'm starting to think its fake It's either that or the codespace is not available I don't even think they care they just thinks fun to troll people and waste their time. They don't even reply to any of the issues people have sent.

**Comment by ccxrc** [comment]
It was working because i had used it like a weeks ago but now that i go and use it it does have a port  n the terminal

**Comment by feeshmaster** [comment]
Yea it used to work
