### ISSUE TITLE
Still having problems

### ISSUE THREAD

**Issue by KyceAbdallah** [thegreatestgiant/novnc#19]
@thegreatestgiant Sorry to bother you, but I'm still having problems that the container won't build but the codespace will boot in recovery mode and still won't work.

Here's the information it tells me when it fails

```
at async Kf (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:4775)
    at async xne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2156:12125)
    at async wne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2156:11866)
devcontainer process exited with exit code 1
Failed to create container.
Error: An error occurred setting up the container.
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.
```

Here's some information from the creation log _I'll also attach the entire creation log so you can look at it if you like_:

```
2023-08-25 15:57:26.832Z: Creating container...
2023-08-25 15:57:26.834Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/novnc --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/novnc/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2023-08-25 15:57:27.036Z: @devcontainers/cli 0.48.0. Node.js v18.17.1. linux 5.15.0-1041-azure x64.
2023-08-25 15:57:27.463Z: $alpine -c echo Container started
2023-08-25 15:57:27.495Z: Unable to find image 'mcr.microsoft.com/devcontainers/base:alpine' locally
```
After looking in my devcontainer file, it recommended I install Microsoft's docker app, and after doing so, it showed me 4 problems within the devcontainer.json file: 
![image](https://github.com/thegreatestgiant/novnc/assets/90739617/f81ad918-720f-415d-a706-41acb2054d31)

Thank you in advance, I hope this, in the end, helps solve all of the problems that it is having, and again, sorry if I was a bother.

**Comment by thegreatestgiant** [comment]
You can try changing the devcontainer.json file yourself and see if that works after you build, but I think the issue is with the docker container itself which is out of date (not my container)
Also thanks for the notes, I really like them

**Comment by KyceAbdallah** [comment]
> You can try changing the devcontainer.json file yourself and see if that works after you build, but I think the issue is with the docker container itself which is out of date (not my container) Also thanks for the notes, I really like them

Yeah I would but Idk how to code at all that's why I was trying to be as descriptive as I could with the notes *Your welcome btw*

**Comment by feeshmaster** [comment]
> You can try changing the devcontainer.json file yourself and see if that works after you build, but I think the issue is with the docker container itself which is out of date (not my container)
> Also thanks for the notes, I really like them

Ok i did a fix on it on my personal computer and it worked with a little change to the devcontainer.json file, but as soon as you put it into a github code space, it doesn’t work. I think github might actually be blocking it because it uses a lot of resources or something like that, but Im still gonna keep trying because there is documentation on it and it is supposed to work.

**Comment by feeshmaster** [comment]
> > You can try changing the devcontainer.json file yourself and see if that works after you build, but I think the issue is with the docker container itself which is out of date (not my container)
> > Also thanks for the notes, I really like them
> 
> Ok i did a fix on it on my personal computer and it worked with a little change to the devcontainer.json file, but as soon as you put it into a github code space, it doesn’t work. I think github might actually be blocking it because it uses a lot of resources or something like that, but Im still gonna keep trying because there is documentation on it and it is supposed to work.

I got it to work. I can give y’all a new link for it once i have it fully done

**Comment by KyceAbdallah** [comment]
> > > You can try changing the devcontainer.json file yourself and see if that works after you build, but I think the issue is with the docker container itself which is out of date (not my container)
> > > Also thanks for the notes, I really like them
> > 
> > 
> > Ok i did a fix on it on my personal computer and it worked with a little change to the devcontainer.json file, but as soon as you put it into a github code space, it doesn’t work. I think github might actually be blocking it because it uses a lot of resources or something like that, but Im still gonna keep trying because there is documentation on it and it is supposed to work.
> 
> I got it to work. I can give y’all a new link for it once i have it fully done

Please do that would be amazing

**Comment by YuviS1123** [comment]
> > > You can try changing the devcontainer.json file yourself and see if that works after you build, but I think the issue is with the docker container itself which is out of date (not my container)
> > > Also thanks for the notes, I really like them
> > 
> > 
> > Ok i did a fix on it on my personal computer and it worked with a little change to the devcontainer.json file, but as soon as you put it into a github code space, it doesn’t work. I think github might actually be blocking it because it uses a lot of resources or something like that, but Im still gonna keep trying because there is documentation on it and it is supposed to work.
> 
> I got it to work. I can give y’all a new link for it once i have it fully done

Please do so, that would be very much appreciated.
