### ISSUE TITLE
Ports

### ISSUE THREAD

**Issue by jerry707777** [thegreatestgiant/novnc#2]
When I click on the ports tab, it doesn't show the 6080 port. It only shows my auto port. When I add a port with the number 6080, it says unable to forward localhost:6080. Can you fix this?

**Comment by Garnsha011** [comment]
My issue with this is when i open it in my chriome browser it says: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-783591ab684acabf1b81b18f79b0e042-64aac9e606693831-00"} so i would appreciate help with this...

**Comment by Garnsha011** [comment]
I meant chrome not chriome

**Comment by spoopyhackerman420** [comment]
it keeps crashing and i dont know why
