### ISSUE TITLE
Bru the thing disconnects after a while and I have to go back in which is super annoying and it disrupts anything running in the terminal so sad.

### ISSUE THREAD

**Issue by Weeblizer-1** [thegreatestgiant/novnc#3]
Dang that was along title but actually is there anything I can do about this? I think it is because my codespace ends and I need to restart it, but can I prevent it from ending so that I don't disconnect.

**Comment by Zapthecat** [comment]
I know that happens to me too

**Comment by Weeblizer-1** [comment]
is there anything I can do?

**Comment by Zapthecat** [comment]
I go back to the code space every like 10 minutes so it doesn’t automatically close

**Comment by BadKarma-rgb** [comment]
I think you add this to the syslog:


Nov 20 22:43:24 pve3-g5 pvedaemon[48920]: <root@pam> end task UPID:pve3-g5:0000E61B:0008F429:6199BCB1:vncproxy:211:root@pam: OK
Nov 20 22:44:01 pve3-g5 pvedaemon[68300]: starting vnc proxy UPID:pve3-g5:00010ACC:000A7161:6199C081:vncproxy:211:root@pam:
Nov 20 22:44:01 pve3-g5 pvedaemon[48920]: <root@pam> starting task UPID:pve3-g5:00010ACC:000A7161:6199C081:vncproxy:211:root@pam:
Nov 20 22:44:22 pve3-g5 pvedaemon[1982]: <root@pam> end task UPID:pve3-g5:0000E820:00090A9A:6199BCEB:vncproxy:211:root@pam: OK
Nov 20 22:44:54 pve3-g5 pvedaemon[51026]: <root@pam> starting task UPID:pve3-g5:00010CD4:000A85EC:6199C0B6:vncproxy:211:root@pam:
Nov 20 22:44:54 pve3-g5 pvedaemon[68820]: starting vnc proxy UPID:pve3-g5:00010CD4:000A85EC:6199C0B6:vncproxy:211:root@pam:
Nov 20 22:45:14 pve3-g5 pvedaemon[48920]: <root@pam> end task UPID:pve3-g5:0000EA57:0009216C:6199BD25:vncproxy:211:root@pam: OK
Nov 20 22:45:47 pve3-g5 pvedaemon[69363]: starting vnc proxy UPID:pve3-g5:00010EF3:000A9A93:6199C0EB:vncproxy:211:root@pam:
Nov 20 22:45:47 pve3-g5 pvedaemon[51026]: <root@pam> starting task UPID:pve3-g5:00010EF3:000A9A93:6199C0EB:vncproxy:211:root@pam:
Nov 20 22:46:14 pve3-g5 pvedaemon[1982]: <root@pam> end task UPID:pve3-g5:0000EC50:00093586:6199BD59:vncproxy:211:root@pam: OK
Nov 20 22:46:44 pve3-g5 pvedaemon[51026]: <root@pam> starting task UPID:pve3-g5:00011171:000AB0FB:6199C124:vncproxy:211:root@pam:
Nov 20 22:46:44 pve3-g5 pvedaemon[70001]: starting vnc proxy UPID:pve3-g5:00011171:000AB0FB:6199C124:vncproxy:211:root@pam:
Nov 20 22:47:09 pve3-g5 pvedaemon[51026]: <root@pam> end task UPID:pve3-g5:0000EE6F:00094D13:6199BD95:vncproxy:211:root@pam: OK
Nov 20 22:47:37 pve3-g5 pvedaemon[70571]: starting vnc proxy UPID:pve3-g5:000113AB:000AC56B:6199C159:vncproxy:211:root@pam:
Nov 20 22:47:37 pve3-g5 pvedaemon[51026]: <root@pam> starting task UPID:pve3-g5:000113AB:000AC56B:6199C159:vncproxy:211:root@pam:
Nov 20 22:48:02 pve3-g5 pvedaemon[48920]: <root@pam> end task UPID:pve3-g5:0000F06B:000962AB:6199BDCC:vncproxy:211:root@pam: OK
Nov 20 22:48:04 pve3-g5 pvedaemon[1982]: worker exit
Nov 20 22:48:04 pve3-g5 pvedaemon[1980]: worker 1982 finished
Nov 20 22:48:04 pve3-g5 pvedaemon[1980]: starting 1 worker(s)
Nov 20 22:48:04 pve3-g5 pvedaemon[1980]: worker 70848 started
Nov 20 22:48:28 pve3-g5 pvedaemon[51026]: <root@pam> starting task UPID:pve3-g5:000115C2:000AD96B:6199C18C:vncproxy:211:root@pam:
Nov 20 22:48:28 pve3-g5 pvedaemon[71106]: starting vnc proxy UPID:pve3-g5:000115C2:000AD96B:6199C18C:vncproxy:211:root@pam:
Nov 20 22:49:26 pve3-g5 pvedaemon[70848]: <root@pam> starting task UPID:pve3-g5:00011817:000AF056:6199C1C6:vncproxy:211:root@pam:
Nov 20 22:49:26 pve3-g5 pvedaemon[71703]: starting vnc proxy UPID:pve3-g5:00011817:000AF056:6199C1C6:vncproxy:211:root@pam:
Nov 20 22:49:52 pve3-g5 pvedaemon[48920]: <root@pam> end task UPID:pve3-g5:0000F49D:00098DBB:6199BE3B:vncproxy:211:root@pam: OK

**Comment by Bradenandme** [comment]
LMAO
