### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by ghost** [thegreatestgiant/novnc#7]
it started being unable to connect even though my Wi-Fi is fine and it keeps on saying "504 gateway timeout" and something with it can't provide a connection or is taking too long to load.. can anyone tell me whats up with that?!
![Screenshot 2023-05-21 9 41 50 PM](https://github.com/thegreatestgiant/novnc/assets/134077167/6ceb88ff-71af-4833-999d-7e7ea2277d34)

**Comment by bradenandkadein** [comment]
yes it does that for me too

**Comment by bradenandkadein** [comment]
@thegreatestgiant pls help us can you fix that ppls mine says 504 gateway timeout too
